### ISSUE TITLE
Colaboradores

### ISSUE THREAD

**Issue by eon0111** [RubaGarcia/Observatorivm#1]
Solicito que se me haga colaborador del presente repositorio, al pertenecer también a mi persona la autoría de los ficheros y directorios que en el se hospedan. XD

uwuwuwuwuwuwuwuwuwuwuwuwuwuwuwuwu

**Comment by RubaGarcia** [comment]
de verdad, lo que tiene que aguantar uno.

Cuando llegue a casa te hago colaborador

**Comment by RubaGarcia** [comment]
Ya habeis sido invitados como colaboradores tu y @pdm858
